version: '3'

tasks:
  check:
    desc: Check for issues
    cmds:
      - npm run prettier -- --check

  fix:
    desc: Fix issues
    cmds:
      - npm run prettier -- --write

  build:
    desc: Build the example
    cmds:
      - rm -rf public/pkg
      - npm run wasm
      - npm run build



