version: '3'

tasks:
  install-ci:
    cmds:
      - pnpm install --frozen-lockfile
  build:
    desc: Build the example
    cmds:
      - rm -rf public/pkg
      - pnpm run wasm
      - pnpm run build


