version: '3'

includes:
  cargo:
    taskfile: ../../node_modules/mono-dev/task/cargo.yaml
    internal: true
    optional: true

tasks:
  check:
    - task: cargo:clippy-all
    - task: cargo:fmt-check
  fix:
    - task: cargo:fmt-fix
