minimumReleaseAgeExclude:
  - '@pistonite/*'

allowBuilds:
  esbuild: true

packages:
  # - example
  - packages/dispatcher
  - packages/test
  # - packages/test-panic-unwind

catalog:
  mono-dev: github:pistonight/mono-dev#dist
  '@types/node': ^24
  "@playwright/test": "^1.62.1"
