version: '3'

includes:
  example:
    aliases: [ex]
    taskfile: ./example
    dir: ./example

  cargo:
    taskfile: ./mono-dev/task/cargo.yaml
    internal: true

tasks:
  install-cargo-extra-tools:
    aliases: [icets]
    cmds:
      - cargo install txtpp

  install:
    cmds:
      - rm -rf mono-dev
      - git clone https://github.com/Pistonight/mono-dev --depth 1
      - echo "nightly" > example/rust-toolchain
      - echo "nightly" > rust-toolchain

  build:
    desc: Incrementally dev build
    cmds:
      - txtpp src/js/createDispatcher.min.js
      - cd example && pnpm run wasm

  check:
    desc: Check for issues
    cmds:
      - task: cargo:clippy-all
      - task: cargo:fmt-check
      - txtpp verify src -r

  fix:
    desc: Fix issues
    cmds:
      - task: cargo:fmt-fix
      - txtpp src -r
