version: '3'

includes:
  # example:
  #   aliases: [ex]
  #   taskfile: ./example
  #   dir: ./example
  #
  common:
    taskfile: ./node_modules/mono-dev/task/common.yaml
    flatten: true
    optional: true

  cargo:
    taskfile: ./node_modules/mono-dev/task/cargo.yaml
    internal: true
    optional: true

  disp:    { taskfile: packages/dispatcher, dir: packages/dispatcher, internal: true }
  example: { taskfile: packages/example,    dir: packages/example,    internal: true }
  lib:     { taskfile: packages/lib,        dir: packages/lib,        internal: true }
  test:    { taskfile: packages/test,       dir: packages/test,       internal: true }
    

tasks:
  install:
    cmds:
      - pnpm install
      - echo "nightly" > rust-toolchain

  check:
    - task: disp:check
    - task: disp:build
    - task: lib:check
    - task: example:check
    - task: test:check
    
