version: '3'

includes:
  common:
    taskfile: ./node_modules/mono-dev/task/common.yaml
    flatten: true
    optional: true

  cargo:
    taskfile: ./node_modules/mono-dev/task/cargo.yaml
    internal: true
    optional: true

  disp:    { taskfile: packages/dispatcher, dir: packages/dispatcher, internal: true }
  example: { taskfile: packages/example,    dir: packages/example,    internal: true }
  lib:     { taskfile: packages/lib,        dir: packages/lib,        internal: true }
  test:    { taskfile: packages/test,       dir: packages/test,       internal: true }
  website: { taskfile: packages/website,    dir: packages/website,    internal: true }
  docs:    { taskfile: packages/docs,       dir: packages/docs,       internal: true }
    

tasks:
  install-cargo-extra-tools:
    aliases: [icets]
    cmds:
      # requires edge wasm-pack for a newer version of binaryen
      - cargo install wasm-pack --git https://github.com/wasm-bindgen/wasm-pack --branch master
      - cargo binstall shwoop mdbook
  install:
    cmds:
      - pnpm install
      - echo "nightly" > rust-toolchain

  check:
    - task: disp:check
    - task: disp:build
    - task: lib:check
    - task: example:check
    - task: test:check
    - task: website:check
    
  build-doc:
    - task: docs:build
