version: '3'

includes:
  example:
    aliases: [ex]
    taskfile: ./example
    dir: ./example


tasks:
  build:
    desc: Incrementally dev build
    cmds:
      - txtpp src/js/createDispatcher.min.js
      - cd example && npm run wasm

  example:
    desc: Build the example into docs folder
    cmds:
      - task: ex:build
      - cp -r example/dist/* docs/

  check:
    desc: Check for issues
    cmds:
      - cargo clippy --all-features --all-targets -- -D warnings -D clippy::todo
      - cargo fmt --check
      - task: prettier
        vars:
          PRETTIER_ARGS: --check
      - txtpp verify src -r

  fix:
    desc: Fix issues
    cmds:
      - cargo fmt
      - task: prettier
        vars:
          PRETTIER_ARGS: --write
      - txtpp src -r

  prettier:
    cmds:
      - npx prettier "./src/js/*.js" --tab-width 4 --end-of-line auto {{.PRETTIER_ARGS}}


