/// <reference types="node" />

// this is a primitive parsing of the rust source
// to generate type safe glue for the dispatcher implementation
// we could use something more robust like syn but it will be really
// complicated

import path from "node:path";
import fs from "node:fs";

const RUST_SRC = path.resolve(import.meta.dirname, "../lib/src");
const RUST_BINDING = path.resolve(RUST_SRC, "binding.rs");
const OUTPUT = path.resolve(import.meta.dirname, "src", "binding.gen.ts");

const main = (): number => {
    if (!fs.existsSync(RUST_BINDING)) {
        throw new Error("cannot find binding.rs");
    }
    const binding_file_lines = fs.readFileSync(RUST_BINDING, { encoding: "utf8" }).split("\n");
    const export_decls = parse_extern_block_in_binding_file(binding_file_lines);
    const export_funcs = parse_export_functions(binding_file_lines);

    const js_arg_types: JsArgType[] = [];
    for (const file_name of fs.readdirSync(RUST_SRC)) {
        const file_lines = fs
            .readFileSync(path.resolve(RUST_SRC, file_name), { encoding: "utf8" })
            .split("\n");
        js_arg_types.push(...parse_js_arg_vecs(file_lines));
    }

    const output = [
        "/** Generated by build.ts */",
        "",
        "declare const RustType: unique symbol;",
        "export type NonNull<T> = number & { readonly [RustType]: T };",
        "export type Option<T> = T | undefined;",
        "",
        "// section: extern block",
        ...export_decls.map((x) => `export type WasmBindgenExport__${x} = WasmBindgen["${x}"]`),
        "",
        "// section: wasm bindgen exports",
        "export interface WasmBindgen {",
        "    /** The wasm_bindgen init function */",
        `    (init: { memory: WebAssembly.Memory; module_or_path: WebAssembly.Module }): Promise<void>;`,
    ];

    for (const { doc, ident, args, retty } of export_funcs) {
        output.push("");
        if (doc.length <= 1) {
            output.push(`    /** ${doc.join("")} */`);
        } else {
            output.push("    /**");
            for (const line of doc) {
                output.push(`     * ${line.trim()}`);
            }
            output.push("     */");
        }
        output.push(`    ${ident}(`);
        for (const { ident, ty } of args) {
            output.push(`        ${ident}: ${ty},`);
        }
        output.push(`    ): ${retty};`);
    }

    output.push("}", "", "// section: js_arg_types");
    for (const { ident, elems } of js_arg_types) {
        output.push(`export type ${ident} = [`);
        for (const { ident, ty } of elems) {
            output.push(`    ${ty}, /* ${ident} */`);
        }
        output.push("];", "");
    }

    fs.writeFileSync(OUTPUT, output.join("\n"));
    return 0;
};

const parse_extern_block_in_binding_file = (binding_file_lines: string[]) => {
    let i = 0;
    for (; i < binding_file_lines.length - 1; i++) {
        if (
            binding_file_lines[i].trim() === "#[wasm_bindgen]" &&
            binding_file_lines[i + 1].trim() === 'extern "C" {'
        ) {
            break;
        }
    }
    if (i === binding_file_lines.length - 1) {
        throw new Error("cannot find extern block in binding file");
    }

    const export_decls: string[] = [];
    for (; i < binding_file_lines.length - 1; i++) {
        const line = binding_file_lines[i].trim();
        if (line === "}") {
            break;
        }
        if (line.startsWith("#[wasm_bindgen(")) {
            const metas = line.substring("#[wasm_bindgen(".length, line.length - 2).split(",");
            for (const meta of metas) {
                const [key, value] = meta.split("=");
                switch (key.trim()) {
                    case "js_name": {
                        export_decls.push(value.trim());
                        break;
                    }
                }
            }
            continue;
        }
    }

    return export_decls.filter((x) => x.startsWith("__"));
};

interface WasmBindgenExportFunction {
    doc: string[];
    ident: string;
    args: {
        ident: string;
        ty: string;
    }[];
    retty: string;
}

const parse_export_functions = (binding_file_lines: string[]) => {
    let i = 0;

    const out: WasmBindgenExportFunction[] = [];
    for (; i < binding_file_lines.length - 1; i++) {
        const doc: string[] = [];
        for (; i < binding_file_lines.length - 1; i++) {
            const line = binding_file_lines[i].trim();
            if (line.startsWith("///")) {
                break;
            }
        }
        for (; i < binding_file_lines.length - 1; i++) {
            const line = binding_file_lines[i].trim();
            if (!line.startsWith("///")) {
                break;
            }
            doc.push(line.substring(3).trim());
        }
        for (; i < binding_file_lines.length - 1; i++) {
            const line = binding_file_lines[i].trim();
            if (line === "#[wasm_bindgen]") {
                break;
            }
        }
        i++;
        if (!binding_file_lines[i]?.startsWith("pub fn")) {
            continue;
        }
        let fn_item = "";
        for (; i < binding_file_lines.length - 1; i++) {
            const line = binding_file_lines[i].trim();
            fn_item += line;
            if (line.endsWith("{")) {
                break;
            }
        }
        const parts = fn_item.split("->");
        if (parts.length > 2) {
            throw new Error("currently we cannot parse functions with Fn traits or fn pointers");
        }
        // console.log("parsing fn: " + fn_item);
        const [ident_part, arg_part] = parts[0].split("(", 2);
        const retty = parts[1] ? trimEndWhitespaceAnd(parts[1], "{") : "void";
        const ident = ident_part.trim().substring("pub fn ".length).trim();
        const args = trimEndWhitespaceAnd(trimEndWhitespaceAnd(arg_part, "{"), ")").split(",");
        const arg_parsed: WasmBindgenExportFunction["args"] = [];
        for (const arg of args) {
            if (!arg.trim()) {
                continue;
            }
            // console.log("-- arg:" + arg);
            const [ident, ty] = arg.split(":", 2);
            const ty_trimmed = ty.trim();
            if (!ty_trimmed.startsWith("NonNull<") || !ty_trimmed.endsWith(">")) {
                throw new Error("currently we only support NonNull in WASM API");
            }
            const inner = ty_trimmed.substring("NonNull<".length, ty_trimmed.length - 1).trim();
            arg_parsed.push({
                ident: ident.trim(),
                ty: `NonNull<"${inner}">`,
            });
        }

        out.push({
            doc,
            ident,
            args: arg_parsed,
            retty: retty === "bool" ? "boolean" : retty,
        });
    }

    return out;
};

interface JsArgType {
    ident: string;
    elems: JsArgVecElem[];
}
interface JsArgVecElem {
    ident: string;
    ty: string;
}
const parse_js_arg_vecs = (file_lines: string[]) => {
    let i = 0;
    const out: JsArgType[] = [];
    for (; i < file_lines.length; i++) {
        for (; i < file_lines.length; i++) {
            if (file_lines[i].includes("js_arg_vec!{")) {
                break;
            }
        }
        if (i >= file_lines.length) {
            break;
        }
        let macro_invoke = "";
        for (; i < file_lines.length; i++) {
            const line = file_lines[i].trim();
            macro_invoke += line;
            if (line.endsWith("};")) {
                break;
            }
        }
        // console.log("parsing macro: " + macro_invoke);
        const start_i = macro_invoke.indexOf("js_arg_vec!{");
        macro_invoke = macro_invoke.substring(start_i + "js_arg_vec!{".length);
        const end_i = macro_invoke.indexOf("};");
        macro_invoke = macro_invoke.substring(0, end_i).trim();
        const last_space_i = macro_invoke.lastIndexOf(" ");
        const ty_ident = macro_invoke.substring(last_space_i).trim();
        const as_i = macro_invoke.substring(0, last_space_i).lastIndexOf(" as");
        const middle = trimEndWhitespaceAnd(
            macro_invoke.substring(0, as_i).trim().substring(1),
            "]",
        ).split(",");
        const elems: JsArgVecElem[] = [];
        for (const part of middle) {
            if (!part.trim()) {
                continue;
            }
            const [ident_ty] = part.split("=", 2);
            const [ident, ty] = ident_ty.trim().split(":", 2);
            const ty_trimmed = ty.trim();
            let ty_parsed: string;
            if (ty_trimmed === "&str") {
                ty_parsed = "string";
            } else if (ty_trimmed.startsWith("NonNull<") && ty_trimmed.endsWith(">")) {
                const inner = ty_trimmed.substring("NonNull<".length, ty_trimmed.length - 1).trim();
                ty_parsed = `NonNull<"${inner}">`;
            } else if (ty_trimmed.startsWith("WasmBindgenExport__")) {
                ty_parsed = ty_trimmed;
            } else {
                ty_parsed = ty_trimmed.replaceAll("__", ".");
            }
            elems.push({ ident: ident.trim(), ty: ty_parsed });
        }

        out.push({ ident: ty_ident, elems });
    }

    return out;
};

const trimEndWhitespaceAnd = (text: string, char: string): string => {
    while (true) {
        const prev = text;
        if (text.endsWith(char)) {
            text = text.substring(0, text.length - char.length);
        }
        text = text.trim();
        if (text === prev) {
            return prev;
        }
    }
};

main();
