/// <reference types="node" />

// this is a primitive parsing of the rust source
// to generate type safe glue for the dispatcher implementation
// we could use something more robust like syn but it will be really
// complicated

import path from "node:path";
import fs from "node:fs";

const RUST_SRC = path.resolve(import.meta.dirname, "../lib/src");
const RUST_BINDING = path.resolve(RUST_SRC, "binding.rs");
const RUST_BINDING_CONSTANTS = path.resolve(RUST_SRC, "binding_constants.rs");
const OUTPUT = path.resolve(import.meta.dirname, "src", "binding.gen.ts");

const main = (): number => {
    if (!fs.existsSync(RUST_BINDING)) {
        throw new Error("cannot find binding.rs");
    }
    const binding_file_lines = fs.readFileSync(RUST_BINDING, { encoding: "utf8" }).split("\n");
    const export_decls = parse_extern_block_in_binding_file(binding_file_lines);
    const export_funcs = parse_export_functions(binding_file_lines);
    const binding_consts_file_lines = fs
        .readFileSync(RUST_BINDING_CONSTANTS, { encoding: "utf8" })
        .split("\n");
    const export_consts = parse_export_constants(binding_consts_file_lines);

    const js_arg_types: JsArgType[] = [];
    for (const file_name of fs.readdirSync(RUST_SRC)) {
        const file_lines = fs
            .readFileSync(path.resolve(RUST_SRC, file_name), { encoding: "utf8" })
            .split("\n");
        js_arg_types.push(...parse_js_arg_vecs(file_lines));
    }

    const output = [
        "/** Generated by build.ts */",
        "",
        "declare const __RustTypeId: unique symbol;",
        "/** Opaque rust type represented as a pointer */",
        "export type RustType<T> = number & { readonly [__RustTypeId]: T };",
        "export type Option<T> = T | undefined;",
        "export type bool = boolean;",
        "// A bug in TypeScript DOM lib cause anything to be assignable to WebAssembly.Module",
        "declare const __WebAssemblyModuleTypeId: unique symbol;",
        "export type OpaqueWebAssemblyModule = { readonly [__WebAssemblyModuleTypeId]: unknown };",
        "",
        "// section: extern block",
        ...export_decls.map((x) => `export type WasmBindgenExport__${x} = WasmBindgen["${x}"]`),
        "",
        "// section: constants",
    ];
    for (const { doc, ident, ty, expr } of export_consts) {
        output.push(...format_doc(doc, ""));
        output.push(`export const ${ident}: ${ty} = ${expr};`);
    }
    output.push("", "// section: wasm bindgen exports", "export interface WasmBindgen {");

    for (const { doc, ident, args, retty } of export_funcs) {
        output.push("");
        output.push(...format_doc(doc, "    "));
        output.push(`    ${ident}(`);
        for (const { ident, ty } of args) {
            output.push(`        ${ident}: ${ty},`);
        }
        output.push(`    ): ${retty};`);
    }

    output.push("}", "", "// section: js_arg_types");
    for (const { ident, elems } of js_arg_types) {
        output.push(`export type ${ident} = [`);
        for (const { ident, ty } of elems) {
            output.push(`    ${ty}, /* ${ident} */`);
        }
        output.push("];", "");
    }

    fs.writeFileSync(OUTPUT, output.join("\n"));
    return 0;
};

const parse_extern_block_in_binding_file = (binding_file_lines: string[]) => {
    let i = 0;
    for (; i < binding_file_lines.length - 1; i++) {
        if (
            binding_file_lines[i].trim() === "#[wasm_bindgen]" &&
            binding_file_lines[i + 1].trim() === 'extern "C" {'
        ) {
            break;
        }
    }
    if (i === binding_file_lines.length - 1) {
        return [];
    }

    const export_decls: string[] = [];
    for (; i < binding_file_lines.length - 1; i++) {
        const line = binding_file_lines[i].trim();
        if (line === "}") {
            break;
        }
        if (line.startsWith("#[wasm_bindgen(")) {
            const metas = line.substring("#[wasm_bindgen(".length, line.length - 2).split(",");
            for (const meta of metas) {
                const [key, value] = meta.split("=");
                switch (key.trim()) {
                    case "js_name": {
                        export_decls.push(value.trim());
                        break;
                    }
                }
            }
            continue;
        }
    }

    return export_decls.filter((x) => x.startsWith("__"));
};

interface WasmBindgenExportFunction {
    doc: string[];
    ident: string;
    args: {
        ident: string;
        ty: string;
    }[];
    retty: string;
}

const parse_export_functions = (binding_file_lines: string[]) => {
    let i = 0;

    const out: WasmBindgenExportFunction[] = [];
    for (; i < binding_file_lines.length; i++) {
        const doc: string[] = [];
        for (; i < binding_file_lines.length; i++) {
            const line = binding_file_lines[i].trim();
            if (line.startsWith("///")) {
                break;
            }
        }
        for (; i < binding_file_lines.length; i++) {
            const line = binding_file_lines[i].trim();
            if (!line.startsWith("///")) {
                break;
            }
            doc.push(line.substring(3).trim());
        }
        for (; i < binding_file_lines.length; i++) {
            const line = binding_file_lines[i].trim();
            if (line === "#[wasm_bindgen(skip_typescript)]") {
                break;
            }
        }
        i++;
        if (!binding_file_lines[i]?.startsWith("pub fn")) {
            continue;
        }
        let fn_item = "";
        for (; i < binding_file_lines.length; i++) {
            const line = binding_file_lines[i].trim();
            fn_item += line;
            if (line.endsWith("{")) {
                break;
            }
        }
        const parts = fn_item.split("->");
        if (parts.length > 2) {
            throw new Error("currently we cannot parse functions with Fn traits or fn pointers");
        }
        // console.log("parsing fn: " + fn_item);
        const parenI = parts[0].indexOf("(");
        const ident_part = parts[0].substring(0, parenI);
        const arg_part = parts[0].substring(parenI + 1);
        const retty = parse_rust_type(parts[1] ? trim_end_white_and(parts[1], "{") : "void");
        const ident = ident_part.trim().substring("pub fn ".length).trim();
        let arg_part_trimmed = trim_end_white_and(arg_part, "{");
        if (arg_part_trimmed.endsWith(")")) {
            arg_part_trimmed = arg_part_trimmed.substring(0, arg_part_trimmed.length - 1);
        }
        const args = arg_part_trimmed.split(",");
        const arg_parsed: WasmBindgenExportFunction["args"] = [];
        for (const arg of args) {
            if (!arg.trim()) {
                continue;
            }
            // console.log("-- arg:" + arg);
            const [ident, ty] = arg.split(":", 2);
            const ty_trimmed = ty.trim();
            arg_parsed.push({
                ident: ident.trim(),
                ty: parse_rust_type(ty_trimmed),
            });
        }

        out.push({
            doc,
            ident,
            args: arg_parsed,
            retty: retty === "bool" ? "boolean" : retty,
        });
    }

    return out;
};

interface JsArgType {
    ident: string;
    elems: JsArgVecElem[];
}
interface JsArgVecElem {
    ident: string;
    ty: string;
}
const parse_js_arg_vecs = (file_lines: string[]) => {
    let i = 0;
    const out: JsArgType[] = [];
    for (; i < file_lines.length; i++) {
        for (; i < file_lines.length; i++) {
            if (file_lines[i].includes("js_arg_vec!")) {
                break;
            }
        }
        if (i >= file_lines.length) {
            break;
        }
        let macro_invoke = "";
        for (; i < file_lines.length; i++) {
            const line = file_lines[i].trim();
            macro_invoke += line;
            if (line.endsWith("};")) {
                break;
            }
        }
        // console.log("parsing macro: " + macro_invoke);
        const start_i = macro_invoke.indexOf("js_arg_vec!");
        macro_invoke = macro_invoke
            .substring(start_i + "js_arg_vec!".length)
            .trimStart()
            .substring(1);
        const end_i = macro_invoke.indexOf("};");
        macro_invoke = macro_invoke.substring(0, end_i).trim();
        const last_space_i = macro_invoke.lastIndexOf(" ");
        const ty_ident = macro_invoke.substring(last_space_i).trim();
        const as_i = macro_invoke.substring(0, last_space_i).lastIndexOf(" as");
        const middle = trim_end_white_and(
            macro_invoke.substring(0, as_i).trim().substring(1),
            "]",
        ).split(",");
        const elems: JsArgVecElem[] = [];
        for (const part of middle) {
            if (!part.trim()) {
                continue;
            }
            const [ident_ty] = part.split("=", 2);
            const [ident, ty] = ident_ty.trim().split(":", 2);
            const ty_parsed = parse_rust_type(ty.trim());
            elems.push({ ident: ident.trim(), ty: ty_parsed });
        }

        out.push({ ident: ty_ident, elems });
    }

    return out;
};

interface Constant {
    doc: string[];
    ident: string;
    ty: string;
    expr: string;
}

const parse_export_constants = (file_lines: string[]): Constant[] => {
    const out: Constant[] = [];
    let i = 0;

    for (; i < file_lines.length; i++) {
        const doc: string[] = [];
        for (; i < file_lines.length; i++) {
            const line = file_lines[i].trim();
            if (line.startsWith("///")) {
                break;
            }
        }
        for (; i < file_lines.length; i++) {
            const line = file_lines[i].trim();
            if (!line.startsWith("///")) {
                break;
            }
            doc.push(line.substring(3).trim());
        }
        if (!file_lines[i]?.startsWith("pub const")) {
            continue;
        }
        let const_item = "";
        for (; i < file_lines.length; i++) {
            const line = file_lines[i].trim();
            const_item += line;
            if (line.endsWith(";")) {
                break;
            }
        }
        const_item = const_item.substring("pub const ".length);
        const [ident, ty_and_value] = const_item.split(":", 2);
        if (!ty_and_value) {
            throw new Error("invalid const item: missing type: " + const_item);
        }
        const [ty, value] = ty_and_value.split("=", 2);
        out.push({
            doc,
            ident: ident.trim(),
            ty: parse_rust_type(ty.trim()),
            expr: trim_end_white_and(value, ";"),
        });
    }
    return out;
};

const trim_end_white_and = (text: string, char: string): string => {
    while (true) {
        const prev = text;
        if (text.endsWith(char)) {
            text = text.substring(0, text.length - char.length);
        }
        text = text.trim();
        if (text === prev) {
            return prev;
        }
    }
};

const parse_rust_type = (ty: string): string => {
    switch (ty) {
        case "u32":
            return "number";
        case "bool":
            return "boolean";
    }
    if (ty.startsWith("NonNull<") && ty.endsWith(">")) {
        return `RustType<"${ty}">`;
    }
    if (ty.startsWith("*mut")) {
        const inner = ty.substring("*mut".length).trim();
        return `RustType<"*mut ${inner}">`;
    }

    if (ty.startsWith("js_type!(") && ty.endsWith(")")) {
        return ty.substring("js_type!(".length, ty.length - 1).trim();
    }
    if (ty.startsWith("raw_ptr_type!(") && ty.endsWith(")")) {
        const inner = ty.substring("raw_ptr_type!(".length, ty.length - 1).trim();
        return `RustType<"*mut ${inner}">`;
    }
    return ty;
};

const format_doc = (doc: string[], indent: string): string[] => {
    const output: string[] = [];
    if (doc.length <= 1) {
        output.push(`${indent}/** ${doc.join("")} */`);
    } else {
        output.push(`${indent}/**`);
        for (const line of doc) {
            output.push(`${indent} * ${line.trim()}`);
        }
        output.push(`${indent} */`);
    }
    return output;
};

main();
