version: '3'

includes:
  ecma:
    taskfile: ./node_modules/mono-dev/task/ecma.yaml
    internal: true
    optional: true

tasks:
  check:
    - node build.ts
    - task: ecma:check
  fix:
    - task: ecma:fix
  build:
    - node build.ts
    - task: ecma:lib-build
    # - mkdir dist/bundle
    # - bun build --outfile=dist/bundle/worker.js dist/worker.js
    # - bun build --outfile=dist/bundle/dispatcher.js dist/dispatcher.js
    # - bun build --outfile=dist/bundle/create.js dist/create.js
