//! Worker based multithreading library for Rust and WebAssembly.
//!
//! This uses the WebAssembly [threads proposal](https://github.com/WebAssembly/threads/blob/master/proposals/threads/Overview.md)
//! and shared memory to communicate between workers (once they are started), instead of `postMessage`.
//! The threads proposal is currently in [phase 4](https://webassembly.org/features/) and available in Chrome, Firefox, Safari and Node.js
//!
//! # Supported Environments
//! TODO - Browsers + NodeJS/Bun/Deno
//!
//! # Examples
//!
//! ## Initializing the thread dispatcher
//! ```rust,no_run
//! // Rust-side
//! use wasm_bindgen::prelude::*;
//!
//! // The bg_js variable contains the .js script generated by wasm_bindgen which
//! // is needed to initialize the wasm module in the worker context.
//! // currently if you need to run other initialization in the worker context
//! // you can bundle it in the script as well
//! #[wasm_bindgen]
//! pub async fn init_wasm_bindgen_spawn(bg_js: JsValue) -> Result<(), JsValue> {
//!     // in targets other than "bundler" and "deno", wasm_bindgen provides a binding
//!     // for the compiled wasm module. If you are using one of the unsupported targets,
//!     // you need to also obtain a reference to the wasm module from the JS side
//!     // and pass it in to Rust.
//!     let init = wasm_bindgen_spawn::init_bg_no_modules(bg_js, wasm_bindgen::module());
//!     
//!     // starts the dispatcher worker and wait for it to be ready. Once it is ready,
//!     // spawning new threads use atomics instead of messaging, which works even
//!     // when the JS Event Loop is blocked. This is the only part of the library
//!     // that requires scheduling tasks onto the JS Event Loop
//!     init.start_dispatcher().await?;
//!     Ok(())
//! }
//!
//! #[wasm_bindgen]
//! pub fn spawn_some_threads() {
//!     let handle = wasm_bindgen_spawn::spawn(move || {
//!         /* do something */
//!     });
//!     // block the current context until the thread (running in another worker) finishes
//!     handle.join().unwrap();
//! }
//!
//! #[wasm_bindgen]
//! pub fn uninit() {
//!     // In non-browser environment you may want this to terminate the thread dispatcher
//!     // so the program does not hang.
//!     wasm_bindgen_spawn::terminate_dispatcher();
//! }
//! ```
//! ```typescript
//! // JS-side (using TypeScript)
//! // you may want to start the WASM inside a worker as well
//! // since the browser's main thread cannot be blocked.
//! // Here we will assume the current context can be blocked
//! // and top-level-await is available to simplify the example
//!
//! // since we are using the no-modules target, we will assume the current context
//! // already has the wasm_bindgen variable from the bindgen JS script.
//! declare const wasm_bindgen: any;
//!
//! // initialize the wasm module
//! await wasm_bindgen({ module_or_path: "example_bg.wasm" });
//!
//! // get the raw code of the js generated by wasm_bindgen. Some bundler also
//! // have special syntax for bundling a file as raw string. For example using vite:
//! // import bg_js from "path/to/example.js?raw";
//! const bg_js = await (await fetch("example.js")).text();
//!
//! // initialize the thread dispatcher
//! await wasm_bindgen.init_wasm_bindgen_spawn(bg_js);
//!
//! wasm_bindgen.spawn_some_threads();
//!
//! wasm_bindgen.uninit();
//!
//! ```

#[cfg(all(target_arch = "wasm32", not(target_feature = "atomics"), not(doc)))]
compile_error!(
    "-Ctarget_feature=atomics is not enabled. Please read the README and set the right rustflags"
);

mod spawn;
pub use spawn::{
    SpawnError, ThreadDispatcherInit, init_bg_no_modules, init_bg_web, spawn, spawn_future,
    terminate_dispatcher, try_spawn, try_spawn_future,
};
mod join;
pub use join::JoinHandle;

/// Interop with JS
mod binding;

mod util;
