use std::panic::AssertUnwindSafe;
use std::ptr::NonNull;
use std::sync::atomic::{AtomicUsize, Ordering};
use std::sync::{Mutex, mpsc};

use js_sys::{Function, Promise};
use wasm_bindgen::{JsCast, JsError, JsValue};

use crate::binding::{self, js_arg_vec, js_type};
use crate::binding_constants::{WBG_TARGET_NO_MODULES, WBG_TARGET_WEB};
use crate::join::JoinHandle;
use crate::util::{
    self, DispatchPayload, DispatchReceiver, DispatchSender, SignalSender, ThreadProc,
};

/// Start building a thread dispatcher using the bindgen script from the "no-modules" target.
/// See [`ThreadDispatcherInit`]
pub fn init_bg_no_modules(bg_js: JsValue, wasm_module: JsValue) -> ThreadDispatcherInit {
    ThreadDispatcherInit {
        bg_target: WBG_TARGET_NO_MODULES,
        bg_js,
        wasm_module,
    }
}
/// Start building a thread dispatcher using the bindgen script from the "web" target.
/// See [`ThreadDispatcherInit`]
pub fn init_bg_web(bg_js: JsValue, wasm_module: JsValue) -> ThreadDispatcherInit {
    ThreadDispatcherInit {
        bg_target: WBG_TARGET_WEB,
        bg_js,
        wasm_module,
    }
}

/// Thread dispatcher initialization.
///
/// The thread dispatcher must be initialized prior to spawning threads.
///
/// The thread dispatcher is initialized in 2 phases:
/// 1. Call one of the `init_bg_*` functions to create an instance of `ThreadDispatcherInit`.
/// 2. Use the JS Event Loop to wait for the thread dispatcher to be ready. Calling spawn
///    before the dispatcher is ready may block the JS Event Loop before it creates the worker
///    for the dispatcher or sends the message to the dispatcher and cause a dead lock.
///
/// ## Building `ThreadDispatcherInit`
/// The thread dispatcher requires 2 things to initialize:
/// 1. The bindgen script generated by wasm_bindgen, either using the `no-modules` or the `web`
///    target.
///    - If you use another target, you need simply need to call wasm-bindgen (or wasm-pack)
///      a second time with either `-t no-modules` or `-t web` to generate another bundle
///      that has the bindgen script, and discard the rest of the output since the wasm modules
///      should be exactly the same.
///    - If you have binding to variables in the JS-side (i.e. any `#[wasm_bindgen] extern "C"`
///      block), and need to use them in the thread, you must use the `no-modules` target and bundle
///      those bindings together with the bindgen script. This is because the `no-modules` script
///      is inlined into the worker whereas the `web` script is imported as a module.
/// 2. If you use the `bundler` or `deno` target, you need to obtain an instance of
///    `WebAssembly.Module` yourself, which is the stateless, compiled code of the `_bg.wasm` file.
///    It can be obtained by calling `WebAssembly.compile` or `WebAssembly.compileStreaming` and
///    provide the bytes of the `.wasm` file, or check if your bundler has some special syntax to
///    provide it. See [MDN reference](https://developer.mozilla.org/en-US/docs/WebAssembly/Reference/JavaScript_interface/compile_static)
///
/// To start building the thread dispatcher, call one of the `init_bg_*` functions
/// depending on the format of your bindgen script.
///
/// ```rust,no_run
/// // if --target no-modules:
/// let init = wasm_bindgen_spawn::init_bg_no_modules(my_bindgen_script, wasm_bindgen::module());
/// // if --target web:
/// let init = wasm_bindgen_spawn::init_bg_web(my_bindgen_script, wasm_bindgen::module());
/// // For other targets you need to call wasm-pack a second time either with -t no-modules
/// // or -t web. For bundler and deno, you also need to pass in from the JS side
/// // a WebAssembly.Module since the wasm_bindgen::module binding is not available.
/// let init = wasm_bindgen_spawn::init_bg_web(my_bindgen_script, my_wasm_module);
/// ```
///
/// ## Create and wait for the thread dispatcher to be ready
/// To create the thread dispatcher, call `.create_dispatcher()` on the `ThreadDispatcherInit`
/// instance. Since the thread dispatcher itself is a worker, you need to yield to the JS Event Loop
/// to wait for the worker to start running.
/// ```rust,no_run
/// use wasm_bindgen::prelude::*;
///
/// #[wasm_bindgen]
/// pub async fn init_thread_dispatcher(bg_js: JsValue) -> Result<(), JsValue> {
///     let init = wasm_bindgen_spawn::init_bg_no_modules(bg_js, wasm_bindgen::module());
///     init.create_dispatcher().await?;
///     Ok(())
/// }
/// ```
/// JS side:
/// ```javascript
/// await init_thread_dispatcher(myBgJsScript);
/// ```
///
/// Note this requires adding `wasm-bindgen-futures` or `js-sys` (with `WASM_BINDGEN_USE_JS_SYS=1`),
/// if most of your code is synchronous and you don't want to deal with the extra dependency,
/// use `create_dispatcher_promise` which wraps the future with a promise for you. Note
/// that internally it still uses the runtime provided by `wasm-bindgen-futures` (now `js_sys::futures`).
///
/// ```rust,no_run
/// #[wasm_bindgen]
/// pub fn init_thread_dispatcher(bg_js: JsValue) -> JsValue {
///     let init = wasm_bindgen_spawn::init_bg_no_modules(bg_js, wasm_bindgen::module());
///     // create the dispatcher and send the promise to the JS side
///     init.create_dispatcher_promise().into()
/// }
/// ```
/// JS side:
/// ```javascript
/// // await the promise on the JS side
/// await init_thread_dispatcher(myBgJsScript);
/// ```
///
/// ## Terminating the thread dispatcher
/// Having the thread dispatcher alive will keep the JS Event Loop alive, which will prevent
/// non-browser runtimes such as NodeJS from exiting. In this case you need to manually call
/// [`wasm_bindgen_spawn::terminate_dispatcher`](crate::terminate_dispatcher) to drop
/// the thread dispatcher which in turn causes the dispatcher worker to terminate.
#[must_use = "This is the builder and the thread dispatcher is not created until you call create_dispatcher() or create_dispatcher_promise() and wait on the future/promise"]
pub struct ThreadDispatcherInit {
    /// Target enum for wasm_bindgen, used to determine how the bindgen JS
    /// should be preprocessed
    bg_target: u32,

    /// The bindgen source code, storing it as JsValue since
    /// this is ultimately needs to be passed to the JS side.
    /// If it's passed from JS side then we save some encoding/decoding cost
    bg_js: JsValue,

    /// The current WebAssembly.Module
    wasm_module: JsValue,
}
impl ThreadDispatcherInit {
    /// The same as [`create_dispatcher`](Self::create_dispatcher) but wrap the Rust future
    /// in a JS Promise, which can then be sent back to the JS side and `await`-ed.
    ///
    /// The async Rust version is cleaner and should be preferred unless there is a reason
    /// to not use async Rust. Note interally this uses the async runtime
    /// provided by `wasm-bindgen-futures` (now `js_sys::futures`) which is what the
    /// `#[wasm_bindgen]` macro uses under the hood for async functions.
    pub fn create_dispatcher_promise(self) -> Promise {
        js_sys::futures::future_to_promise(async move {
            self.create_dispatcher().await?;
            Ok(JsValue::undefined())
        })
    }

    /// Spawn the dispatcher worker and wait for it to become ready
    ///
    /// If any JS exceptions occur, it is returned as an `Err`.
    ///
    /// # Panic
    /// Panics if the dispatcher is already initialized. Note you only need to
    /// initialize the dispatcher once across the shared memory instance. You don't need
    /// to initialize it in each thread.
    pub async fn create_dispatcher(self) -> Result<(), JsValue> {
        // we want to be pretty loud since user should not initialize the thread creator more
        // than once in one shared memory instance. Since the memory is shared, all
        // threads can access the dispatcher at the same time (since itself is just a
        // std::sync::mpsc Sender
        {
            let dispatcher_guard = DISPATCHER.lock().expect("cannot lock the dispatcher");
            if dispatcher_guard.is_some() {
                drop(dispatcher_guard);
                panic!("{DISPATCHER_ALREADY_INIT_WARNING}");
            }
        }
        // this function is implemented in dispatcher/src/create.ts
        let create_dispatcher = Function::new_with_args("ARGS", include_str!("dispatcher.js"));
        let (send, recv) = mpsc::channel::<DispatchPayload>();
        let (signal_send, signal_recv) = util::assert_unwind_safe_oneshot_channel::<()>();

        // type alias for generating TypeScript types
        type ThreadCreatorArgs = Vec<JsValue>;
        let creator_args = js_arg_vec! {
            [
                bg_target: js_type!(number) = self.bg_target.into(),
                bg_js: js_type!(string) = self.bg_js,
                wasm_module: js_type!(WebAssembly.Module) = self.wasm_module,
                memory: js_type!(WebAssembly.Memory) = wasm_bindgen::memory(),
                recv_ptr: NonNull<DispatchReceiver> = binding::into_js(recv),
                dispatcher_start_signal_send_ptr: NonNull<SignalSender> = binding::into_js(signal_send),
            ] as ThreadCreatorArgs
        };

        // create the dispatcher
        let _ = create_dispatcher
            .call1(&JsValue::null(), &JsValue::from(creator_args))?
            .dyn_into::<Promise>()?
            .await?;
        // we need to poll the signal to ensure the postMessage
        // has fired and the dispatcher is now blocked on waiting for spawn requests.
        // Otherwise, this context can be blocked by caller and dispatcher never
        // receives the initialize message

        // yield to the JS Runtime so it can process the worker creation, etc.
        // It is implementation-dependent if Worker can start execution immediately
        // or after the current context. Currently all mainstream implementation
        // only start the Worker after the current context is done. This means
        // we will most likely have to wait at least once
        let yield_fn = Function::new_no_args("return new Promise(r=>setTimeout(r,0))");
        yield_fn
            .call0(&JsValue::null())?
            .dyn_into::<Promise>()?
            .await?;
        loop {
            match signal_recv.try_recv() {
                Err(oneshot::TryRecvError::Empty) => {
                    yield_fn
                        .call0(&JsValue::null())?
                        .dyn_into::<Promise>()?
                        .await?;
                }
                Err(oneshot::TryRecvError::Disconnected) => {
                    return Err(JsError::new(
                        "The wasm-bindgen-spawn thread dispatcher disconnected!",
                    )
                    .into());
                }
                _ => break,
            }
        }
        {
            let mut dispatcher_guard = DISPATCHER.lock().expect("cannot lock the dispatcher");
            if dispatcher_guard.is_some() {
                drop(dispatcher_guard);
                panic!("{DISPATCHER_ALREADY_INIT_WARNING}");
            }
            *dispatcher_guard = Some(send);
        }

        Ok(())
    }
}

static NEXT_THREAD_ID: AtomicUsize = AtomicUsize::new(1);
// using a OnceLock to prevent multiple threads calling one of the init functions at the same time
// it should be pretty rare though since downstream user would have to either unknowingly
// call init_bg* multiple times somewhere in Rust, or initializing shared memory themselves in multiple workers
// and both call init_bg*
static DISPATCHER: Mutex<Option<DispatchSender>> = Mutex::new(None);
static DISPATCHER_ALREADY_INIT_WARNING: &str = "The wasm-bindgen-spawn thread dispatcher is already initialized! The dispatcher is a global, in the shared memory, not a thread-local, so all threads have access to it and you do not need to initialize it per-thread";

/// Spawn a new thread similar to [`std::thread::spawn`]
///
/// Conceptually, the new thread will start execute immediately without the need to yield
/// to the JS Event Loop, meaning the spawning thread can block immediately after calling `spawn`
/// to join the spawned thread without causing dead locks.
///
/// The closure `f` will be executed synchronously in the worker's context. When `f` returns
/// a value, the worker is terminated. This means any promise/futures scheduled onto the JS Event
/// Loop will not run and attempting to `await` them inside the thread
/// will cause a dead lock. If you need to spawn a worker thread and run asynchronous JS (i.e. via `js_sys` or `web_sys`),
/// use [`spawn_future`] which accepts a Rust future and will use the worker's JS Event Loop
/// to drive that future.
///
/// # Panic
/// Similar to [`std::thread::spawn`], this function may panic if the thread creation fails,
/// including if the thread dispatcher has not been initialized (see [`ThreadDispatcherInit`]).
/// Use [`try_spawn`] as the recoverable version.
#[inline(always)]
pub fn spawn<F, T>(f: F) -> JoinHandle<T>
where
    F: FnOnce() -> T + Send + 'static,
    T: Send + 'static,
{
    match try_spawn(f) {
        Ok(x) => x,
        Err(e) => panic!("Failed to spawn thread with wasm-bindgen-spawn: {e}"),
    }
}

/// Same as [`spawn`] but captures thread creation failure.
#[inline(always)]
pub fn try_spawn<F, T>(f: F) -> Result<JoinHandle<T>, SpawnError>
where
    F: FnOnce() -> T + Send + 'static,
    T: Send + 'static,
{
    try_spawn_impl(async move { f() })
}

/// Spawn a new thread that uses the JS Event Loop to drive a future.
///
/// Conceptually, the new thread will start execute immediately without the need to yield
/// to the JS Event Loop of the spawning thread, meaning the spawning thread can block immediately after calling `spawn`
/// to join the spawned thread without causing dead locks.
///
/// The spawned future `f` will be driven by the JS Event Loop using the runtime provided by
/// `js_sys::futures` (previously known as `wasm-bindgen-futures`). You can use `js_sys` or
/// `web_sys` to call asynchronous JS APIs and `await` them inside the spawned future.
///
/// # Panic
/// Similar to [`std::thread::spawn`], this function may panic if the thread creation fails,
/// including if the thread dispatcher has not been initialized (see [`ThreadDispatcherInit`]).
/// Use [`try_spawn_future`] as the recoverable version.
#[inline(always)]
pub fn spawn_future<F, T>(f: F) -> JoinHandle<T>
where
    F: Future<Output = T> + Send + 'static,
    T: Send + 'static,
{
    match try_spawn_impl(f) {
        Ok(x) => x,
        Err(e) => panic!("Failed to spawn thread with wasm-bindgen-spawn: {e}"),
    }
}

/// Same as [`spawn_future`] but captures thread creation failure.
#[inline(always)]
pub fn try_spawn_future<F, T>(f: F) -> Result<JoinHandle<T>, SpawnError>
where
    F: Future<Output = T> + Send + 'static,
    T: Send + 'static,
{
    try_spawn_impl(f)
}

/// Spawn a new thread to execute F. Note that spawning a new thread is very
/// expensive, as it requires spinning up a new Worker in JS and waiting for it to be ready
/// to accept the closure `F`. Pool the threads if you can.
fn try_spawn_impl<F, T>(f: F) -> Result<JoinHandle<T>, SpawnError>
where
    F: Future<Output = T> + Send + 'static,
    T: Send + 'static,
{
    let dispatcher = {
        let dispatcher = match DISPATCHER.lock() {
            Err(_) => {
                return Err(SpawnError::DispatcherPoisoned);
            }
            Ok(x) => x,
        };
        let Some(dispatcher) = &*dispatcher else {
            return Err(SpawnError::NotInit);
        };
        dispatcher.clone()
    };

    // assert unwind safety here only to work around wasm_bindgen's
    // requirement that anything crossing JS-Rust boundary needs to be unwind safe.
    // See ThreadProc for explanation of the unwind safety model
    let f_boxed: ThreadProc = AssertUnwindSafe(Box::pin(async move {
        Box::new(f.await).into()
    }));
    let next_id = NEXT_THREAD_ID.fetch_add(1, Ordering::Relaxed);
    let (send, recv) = util::assert_unwind_safe_oneshot_channel();
    dispatcher
        .send((f_boxed, send))
        .map_err(|_| SpawnError::Disconnected)?;
    Ok(JoinHandle::new(next_id, recv))
}

/// Thread creation error returned by [`try_spawn`] or [`try_spawn_future`]
#[derive(Debug, thiserror::Error)]
pub enum SpawnError {
    /// The thread dispatcher is not initialized
    #[error(
        "The wasm-bindgen-spawn thread dispatcher was not initialized. You must call one of the wasm_bindgen_spawn::init_bg_* functions before spawning threads"
    )]
    NotInit,
    /// The thread dispatcher is poisoned because a panic is observed while spawning a thread
    #[error("The wasm-bindgen-spawn thread dispatcher was poisoned.")]
    DispatcherPoisoned,
    /// The thread dispatcher is unexpectedly disconnected
    #[error("The wasm-bindgen-spawn thread dispatcher has disconnected")]
    Disconnected,
}

/// Terminate the thread dispatcher worker
///
/// This is useful in native JS runtimes such as NodeJS to manually uninitialize and finalize
/// the threading system to allow the program to terminate, since JS engines will not terminate
/// unless the event loop has exhausted, which will not happen unless all workers are terminated.
///
/// It's generally NOT recommended to call this unless all threads have been joined. The dispatcher
/// is responsible for recovering from hard aborts (even when `panic=unwind`). After the dispatcher
/// is terminated, threads that complete successfully or whose panics are caught with `catch_unwind`
/// can still be `join`-ed, but threads that hard panicked may hang.
///
/// After termination, attempt to `spawn` new threads will panic (or return `Err` when using the `try_` variants).
///
/// Under the hood, the handle to the thread dispatcher in Rust is dropped. This wakes
/// the dispatcher worker which then posts a message to the main thread (the one that called
/// [`create_dispatcher`](ThreadDispatcherInit)) to terminate it.
pub fn terminate_dispatcher() {
    if let Ok(mut dispatcher) = DISPATCHER.lock() {
        *dispatcher = None;
    }
}
