import { describe, it, expect } from "mono-dev/vitest";

import { readLogFile } from "#framework";

import { LOG_PATHS, pickEntries, pickValues } from "./util.ts";

// Generated by LLM

const THREADS = 30;

describe.each(LOG_PATHS)("%s", (logPath) => {
    const run = readLogFile(logPath);
    if (run.engine === "deno") {
        it("skips deno due to slow worker", () => {});
        return;
    }
    const log = run.getTestLog("example_arc_atomic");

    const increments = pickEntries(log.entries, "prev");
    const beforeJoin = pickEntries(log.entries, "sum_before_join");
    const afterJoin = pickEntries(log.entries, "sum_after_join");

    it("incremented atomicly", () => {
        expect(afterJoin.length).toBe(1);
        expect(afterJoin[0].isMainThread()).toBe(true);
        expect(afterJoin[0].payload.sum_after_join).toBe(THREADS);
    });

    it("each thread did a distinct fetch_add", () => {
        expect(increments.length).toBe(THREADS);
        const values = pickValues(increments, "prev");
        expect(values.slice().sort((a, b) => a - b)).toEqual(
            Array.from({ length: THREADS }, (_, i) => i),
        );
    });

    it("each thread has unique id", () => {
        // one entry per thread, and 30 different threads - the increments
        // really are spread over 30 workers rather than replayed on one of them
        expect(new Set(increments.map((x) => x.thread)).size).toBe(increments.length);
        for (const e of increments) {
            expect(e.isMainThread()).toBe(false);
        }
    });

    it("read the counter before joining, while threads were still running", () => {
        expect(beforeJoin.length).toBe(1);
        expect(beforeJoin[0].isMainThread()).toBe(true);
        const sum = beforeJoin[0].payload.sum_before_join;

        // main reads the counter right after the spawn loop, so it cannot have
        // seen all 30 increments - joining is what makes the count complete.
        //
        // in practice, every engine logs 0 here since the overhead of
        // starting a worker is extremely high

        // expect(sum).toBeLessThan(THREADS);
        // expect(sum).toBeGreaterThanOrEqual(0);
        expect(sum).toBe(0);
    });

    it("did not panic", () => {
        expect(log.entries.filter((x) => x.panic).length).toBe(0);
    });
});
