import { describe, it, expect } from "mono-dev/vitest";

import { readLogFile, type LogEntry } from "#framework";

import {
    LOG_PATHS,
    entriesFromThread,
    findEntry,
    pickEntries,
    pickValues,
    timestampsOf,
} from "./util.ts";

// Generated by LLM

/** the delay each thread sleeps between sends, see the example */
const SLEEP_MS = 500;
/**
 * Bounds we allow for one sleep to take.
 *
 * The sleep itself is accurate to a fraction of a millisecond on every engine,
 * but the harness log call around it costs ~100ms in browsers, so the observed
 * gap between 2 sends is 500-604ms depending on the engine. The upper bound is
 * loose on purpose, so a loaded CI machine doesn't fail the run.
 */
const SLEEP_MIN_MS = 450;
const SLEEP_MAX_MS = 1500;

/** the number of threads spawned, and the number of values each one sends */
const THREADS = 3;
const SENDS_PER_THREAD = 3;

describe.each(LOG_PATHS)("%s", (logPath) => {
    const run = readLogFile(logPath);
    const log = run.getTestLog("example_mpsc_channel");

    const spawns = pickEntries(log.entries, "spawning_thread");
    const starts = pickEntries(log.entries, "thread_start");
    const sends = pickEntries(log.entries, "thread_sending");
    const dones = pickEntries(log.entries, "thread_done");
    const receives = pickEntries(log.entries, "received");

    /** entries logged by the thread that ran the closure for `i` */
    const entriesOf = (entries: LogEntry[], i: number): LogEntry[] => {
        // which OS thread that is isn't the same across engines
        const thread = findEntry(starts, "thread_start", i).thread;
        return entriesFromThread(entries, thread);
    };
    /** the values thread `i` is expected to send, in order */
    const payloadsOf = (i: number): number[] =>
        Array.from({ length: SENDS_PER_THREAD }, (_, j) => i * SENDS_PER_THREAD + j);

    it("spawned 3 threads", () => {
        expect(spawns.length).toBe(THREADS);
        for (const e of spawns) {
            expect(e.isMainThread()).toBe(true);
        }
        // should spawn in order
        expect(pickValues(spawns, "spawning_thread")).toEqual([0, 1, 2]);
    });

    it("started 3 threads", () => {
        expect(starts.length).toBe(THREADS);
        // note we sort here - the threads are spawned in order, but which one
        // wins the race to start first is up to the engine
        expect(pickValues(starts, "thread_start").sort((a, b) => a - b)).toEqual([0, 1, 2]);

        // each thread must be a distinct worker, and none of them the main thread
        expect(new Set(starts.map((x) => x.thread)).size).toBe(THREADS);
        for (const e of starts) {
            expect(e.isMainThread()).toBe(false);
        }

        // a thread can only start after main spawned it
        for (let i = 0; i < THREADS; i++) {
            const spawned = findEntry(spawns, "spawning_thread", i);
            const started = findEntry(starts, "thread_start", i);
            expect(started.timestamp).toBeGreaterThanOrEqual(spawned.timestamp);
        }
    });

    it("each thread sent its 3 values in order", () => {
        expect(sends.length).toBe(THREADS * SENDS_PER_THREAD);
        expect(dones.length).toBe(THREADS);
        for (let i = 0; i < THREADS; i++) {
            expect(pickValues(entriesOf(sends, i), "thread_sending")).toEqual(payloadsOf(i));
            expect(pickValues(entriesOf(dones, i), "thread_done")).toEqual([i]);
        }
    });

    it("received every value exactly once on the main thread", () => {
        expect(receives.length).toBe(THREADS * SENDS_PER_THREAD);
        for (const e of receives) {
            expect(e.isMainThread()).toBe(true);
        }
        const values = pickValues(receives, "received");
        expect(values.sort((a, b) => a - b)).toEqual([0, 1, 2, 3, 4, 5, 6, 7, 8]);
    });

    it("received each thread's values in the order they were sent", () => {
        // only the per-sender order is checked here. the global order across
        // senders is deliberately not asserted: `thread_sending` is logged
        // *before* the actual send, so two threads sending at the same time can
        // log in one order and enqueue in the other - which msedge really does.
        for (let i = 0; i < THREADS; i++) {
            const values = pickValues(receives, "received").filter(
                (x) => Math.floor(x / SENDS_PER_THREAD) === i,
            );
            expect(values).toEqual(payloadsOf(i));
        }
    });

    it("received each value after it was sent", () => {
        for (const e of receives) {
            const sent = findEntry(sends, "thread_sending", e.payload?.received as number);
            expect(e.timestamp).toBeGreaterThanOrEqual(sent.timestamp);
        }
    });

    it("slept between sends", () => {
        for (let i = 0; i < THREADS; i++) {
            // the thread sleeps before every send, including the first one,
            // so the start of the thread counts as a boundary here
            const timestamps = timestampsOf([...entriesOf(starts, i), ...entriesOf(sends, i)]);
            for (let j = 1; j < timestamps.length; j++) {
                const gap = timestamps[j] - timestamps[j - 1];
                expect(gap).toBeGreaterThanOrEqual(SLEEP_MIN_MS);
                expect(gap).toBeLessThanOrEqual(SLEEP_MAX_MS);
            }
        }
        // main can't have finished before the threads slept 3 times
        expect(log.duration).toBeGreaterThan(SENDS_PER_THREAD * SLEEP_MIN_MS);
    });

    it("received values while the threads were still sending", () => {
        // main must consume as values arrive rather than draining the channel
        // at the end, so every thread's sending window contains a receive
        for (let i = 0; i < THREADS; i++) {
            const timestamps = timestampsOf(entriesOf(sends, i));
            const first = timestamps[0];
            const last = timestamps[timestamps.length - 1];
            const inWindow = receives.filter((x) => x.timestamp > first && x.timestamp < last);
            expect(inWindow.length).toBeGreaterThan(0);
        }
    });

    it("ran the threads in parallel", () => {
        // when each thread was alive, from its own point of view
        const lifetimes = Array.from({ length: THREADS }, (_, i) => ({
            start: entriesOf(starts, i)[0].timestamp,
            end: entriesOf(dones, i)[0].timestamp,
        }));

        if (run.engine === "deno") {
            // deno takes ~1s to actually start a worker, and serializes the
            // startups, so thread 0 can be done before thread 2 has started.
            // the threads still overlap, just not all 3 at once - so only check
            // that each thread overlaps with the next one to start.
            const byStart = [...lifetimes].sort((a, b) => a.start - b.start);
            for (let i = 1; i < byStart.length; i++) {
                expect(byStart[i].start).toBeLessThan(byStart[i - 1].end);
            }
            return;
        }

        // every other engine starts the workers fast enough that all 3 threads
        // are alive at the same time...
        expect(Math.max(...lifetimes.map((x) => x.start))).toBeLessThan(
            Math.min(...lifetimes.map((x) => x.end)),
        );

        // ...and are all sending at the same time, not just alive
        const windows = Array.from({ length: THREADS }, (_, i) =>
            timestampsOf(entriesOf(sends, i)),
        );
        expect(Math.max(...windows.map((x) => x[0]))).toBeLessThan(
            Math.min(...windows.map((x) => x[x.length - 1])),
        );

        // ...so the whole thing must take less than the 9 sleeps it would cost
        // to run the threads one after another
        expect(log.duration).toBeLessThan(THREADS * SENDS_PER_THREAD * SLEEP_MS);
    });

    it("did not panic", () => {
        expect(log.entries.filter((x) => x.panic).length).toBe(0);
    });
});
