import { it, expect } from "mono-dev/vitest";

import { describeLogTest, only } from "./util.ts";

// Generated by LLM

/** the number of threads spawned, and the number of pushes each one does */
const THREADS = 2;
const COUNT = 5000;

/** the length of the `interleave_sample` slice logged by the example */
const SAMPLE_SIZE = 100;

/**
 * How lopsided the sampled section may be.
 *
 * Both threads sleep the same 1ms between pushes, so over a 100 value window
 * they should contribute ~50 each. only a gross imbalance is rejected here -
 * the observed spread across all engines is 48-51.
 */
const MIN_SHARE_OF_SAMPLE = 30;

/**
 * How many times the lock must change hands inside the sampled section.
 *
 * Perfect alternation gives 99 handoffs over 100 values, which is what every
 * engine very nearly does (95+). the point of the bound is to reject a run that
 * merely happens to contain both values while each thread pushed in big batches.
 */
const MIN_HANDOFFS = 50;

describeLogTest("example_mutex", (log) => {

    const length = only(log.entries, "vec_length").payload?.vec_length as number;
    const pos = only(log.entries, "interleave_pos").payload?.interleave_pos as number;
    const sample = only(log.entries, "interleave_sample").payload
        ?.interleave_sample as number[];

    it("logged correct length", () => {
        expect(length).toBe(THREADS * COUNT);
    });

    it("logged the result from the main thread after joining", () => {
        for (const key of ["vec_length", "interleave_pos", "interleave_sample"]) {
            expect(only(log.entries, key).isMainThread()).toBe(true);
        }
    });

    it("detected interleaving section", () => {
        expect(sample.length).toBe(SAMPLE_SIZE);
        // only the two thread indices ever get pushed
        expect(new Set(sample).size).toBeLessThanOrEqual(THREADS);
        for (const x of sample) {
            expect(x).toBeGreaterThanOrEqual(0);
            expect(x).toBeLessThan(THREADS);
        }
        // the sample starts at the first `1`, by definition
        expect(sample[0]).toBe(1);
        // the position of the first 1 should be less than the number of each index
        expect(pos).toBeLessThan(COUNT);
    });

    it("both threads made progress at the same rate", () => {
        for (let i = 0; i < THREADS; i++) {
            expect(sample.filter((x) => x === i).length).toBeGreaterThanOrEqual(
                MIN_SHARE_OF_SAMPLE,
            );
        }
    });

    it("passed the lock back and forth rather than in batches", () => {
        let handoffs = 0;
        for (let i = 1; i < sample.length; i++) {
            if (sample[i] !== sample[i - 1]) {
                handoffs++;
            }
        }
        expect(handoffs).toBeGreaterThanOrEqual(MIN_HANDOFFS);
    });

    it("did not panic", () => {
        expect(log.entries.filter((x) => x.panic).length).toBe(0);
    });
});
