import { describe, it } from "mono-dev/vitest";

import {
    BROWSER_ENGINES,
    type LogFile,
    NATIVE_ENGINES,
    PANIC_RUNTIMES,
    PROFILES,
    type LogEntry,
    readLogFile,
    type TestLog,
} from "#framework";

export const describeLogTest = (testName: string, testSuiteFn: (log: TestLog, run: LogFile)=>void)  => {
    const logPaths = (process.env.WBS_VITEST_INPUTS || "").split(",");
    const testFilters = (process.env.WBS_VITEST_TEST_FILTERS || "").split(",");
    if (!logPaths.length) {
        throw new Error("invalid test input; tests must run through the wrapper script!");
    }

    let run: boolean;
    if (testFilters.length) {
        run = false;
        for (const filter of testFilters) {
            if (testName.includes(filter)) {
                run = true;
                break;
            }
        } 
    } else {
        run = true;
    }

    if (!run) {
        describe.skip(testName, () => {});
        return;
    }

    describe.each(logPaths)(`${testName} - %s`, (logPath) => {
        let run: LogFile;
        try {
            run = readLogFile(logPath);
        } catch(e) {
            throw new Error("failed to read log: " + logPath, { cause: e });
        }

        if (testName === "example_arc_atomic" && run.engine === "deno") {
            it("skips deno due to slow worker", () => {});
            return;
        }
        const log = run.getTestLog(testName)
        testSuiteFn(log, run);
    });
}

export const LOG_PATHS: string[] = [];
for (const profile of PROFILES) {
    for (const panicRuntime of PANIC_RUNTIMES) {
        for (const target of ["no-modules", "web", "vite"]) {
            for (const engine of BROWSER_ENGINES) {
                LOG_PATHS.push(`${engine}/${profile}-${panicRuntime}-${target}`);
            }
            for (const engine of NATIVE_ENGINES) {
                // bun v1.3.14 currently has a bug where it seg faults when trying to grow shared memory
                if (engine === "bun") {
                    continue;
                }
                LOG_PATHS.push(`${engine}/${profile}-${panicRuntime}-${target}`);
            }
        }
        // nodejs target
        for (const engine of ["node", "bun"]) {
            // bun v1.3.14 currently has a bug where it seg faults when trying to grow shared memory
            if (engine === "bun") {
                continue;
            }
            LOG_PATHS.push(`${engine}/${profile}-${panicRuntime}-nodejs`);
        }
        // deno target
        for (const engine of ["bun", "deno"]) {
            // bun v1.3.14 currently has a bug where it seg faults when trying to grow shared memory
            if (engine === "bun") {
                continue;
            }
            LOG_PATHS.push(`${engine}/${profile}-${panicRuntime}-deno`);
        }
    }
}

// TODO - clean up these utils generated by LLM

/**
 * Get the entries that carry `key` in their payload.
 *
 * Note this checks for the key, not for the value - payload values often start
 * at 0, which is falsy.
 */
export const pickEntries = (entries: LogEntry[], key: string): LogEntry[] =>
    entries.filter((x) => x.payload && key in x.payload);

/** Get the `key` payload value of every entry, in order */
export const pickValues = (entries: LogEntry[], key: string): number[] =>
    entries.map((x) => x.payload?.[key]) as number[];

/** Get the only entry whose `key` payload value is `value` */
export const findEntry = (entries: LogEntry[], key: string, value: number): LogEntry => {
    const found = entries.filter((x) => x.payload && x.payload[key] === value);
    if (found.length !== 1) {
        throw new Error(`expected exactly 1 entry with ${key}=${value}, got ${found.length}`);
    }
    return found[0];
};

/** get the single entry carrying `key` */
export const only = (entries: LogEntry[], key: string): LogEntry => {
    const found = pickEntries(entries, key);
    if (found.length !== 1) {
        throw new Error(`expected exactly 1 entry with ${key}, got ${found.length}`);
    }
    return found[0];
};

/** Get the entries logged by `thread`, in order */
export const entriesFromThread = (entries: LogEntry[], thread: number): LogEntry[] =>
    entries.filter((x) => x.thread === thread);

/** Get the timestamp of every entry, in order */
export const timestampsOf = (entries: LogEntry[]): number[] => entries.map((x) => x.timestamp);
