name: Build
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  check:
    name: Example
    runs-on: ubuntu-latest
    steps:
      - uses: Pistonight/mono-dev/actions/setup@main
        with:
          mono-dev: true
          ecma-pnpm: true
          ecma-bun: true
          rust: nightly
          rust-wasm: true
          rust-src: true
          tool-cargo-binstall: txtpp
      - run: task install-ci
        working-directory: example
      - run: task build
        working-directory: example
      - uses: actions/upload-artifact@v4
        with:
          path: example/dist
          name: example
          retention-days: 3
