name: Build
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  check:
    name: Example
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - uses: dtolnay/rust-toolchain@nightly
        with:
          targets: wasm32-unknown-unknown,rust-src
      - uses: cargo-bins/cargo-binstall@main
      - run: cargo binstall --no-confirm wasm-pack
      - run: npm ci
        working-directory: example
      - run: npm run wasm
        working-directory: example
      - run: npm run build
        working-directory: example
      - uses: actions/upload-artifact@v4
        with:
          path: example/dist
          name: example
          retention-days: 3