name: Check
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: Pistonight/mono-dev/actions/setup@main
        with:
          mono-dev: true
          ecma-pnpm: true
          ecma-bun: true
          rust: nightly
          rust-wasm: true
          rust-src: true
          tool-cargo-binstall: txtpp
      - run: task check
